#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2024.2.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Oct 01 17:37:25 CST 2025
# SW Build 5266912 on Sun Dec 15 09:03:31 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_compute_core_behav -key {Behavioral:sim_1:Functional:tb_compute_core} -tclbatch tb_compute_core.tcl -log simulate.log"
xsim tb_compute_core_behav -key {Behavioral:sim_1:Functional:tb_compute_core} -tclbatch tb_compute_core.tcl -log simulate.log

