// Generated by gen_mats.py or provided test data
test_params_pkg.sv

// Testbench interface and DUT wrapper
tb_compute_core_if.sv
compute_core_test.sv

// Design dependencies in this package
bias_mux.sv
ps_buffer.sv
ps_buffer_fifo.sv
pseudo_dual_port_ram.sv
de_diagonalizer.sv

// Add your project implementation of ws_systolic_array here, for example:
// ../../rtl/ws_systolic_array.sv

// Testbench top
tb_compute_core.sv
