module ps_buffer #(
    parameter int unsigned SIZE       = 16,
    parameter int unsigned DATA_WIDTH = 32
) (
    input  logic                         clk,
    input  logic                         rst_n,
    input  logic signed [DATA_WIDTH-1:0] data_in       [0:SIZE-1],
    input  logic                         ia_row_valid,
    input  logic                         ia_calc_done,
    input  logic                         ia_l1_switch,
    input  logic                         send_ia_trigger,
    input  logic                         ia_is_init_data,
    output logic signed [DATA_WIDTH-1:0] data_out      [0:SIZE-1],
    output logic                         acc_data_valid,
    output logic                         tile_calc_over
);
    // A full diagonal / staircase tile contains 2*SIZE-1 vectors.
    // Keep a little margin for debugging or future non-square tails.
    localparam int unsigned DEPTH = (2 * SIZE) + 4;

    logic signed [DATA_WIDTH-1:0] fifo_data_out    [0:SIZE-1];
    logic signed [DATA_WIDTH-1:0] de_diag_data_out [0:SIZE-1];

    logic                         de_diag_data_valid;
    logic                         de_diag_tile_calc_over;

    // Current contract:
    //   * ia_row_valid entering ps_buffer is already the internal full
    //     partial-sum valid window generated by compute_core_test.
    //   * All lanes receive the same valid/switch/replay controls.
    //   * The stored/replayed FIFO stream is therefore still a diagonalized
    //     vector stream: step0, step1, ..., step(2*SIZE-2).
    //   * calc_done is not propagated through FIFO. When asserted, the current
    //     data bypasses the FIFO write path and enters de_diagonalizer.
    genvar lane;
    generate
        for (lane = 0; lane < SIZE; lane++) begin : gen_ps_buffer_fifo
            ps_buffer_fifo #(
                .DEPTH     (DEPTH),
                .DATA_WIDTH(DATA_WIDTH)
            ) u_ps_buffer_fifo (
                .clk              (clk),
                .rst_n            (rst_n),
                .data_in          (data_in[lane]),
                .input_valid_i    (ia_row_valid & ~ia_calc_done),
                .is_init_data_i   (ia_is_init_data),
                .ia_l1_switch_i   (ia_l1_switch),
                .send_ia_trigger_i(send_ia_trigger),
                .data_out         (fifo_data_out[lane]),
                .input_valid_o    (),
                .is_init_data_o   (),
                .ia_l1_switch_o   (),
                .send_ia_trigger_o()
            );
        end
    endgenerate

    de_diagonalizer #(
        .SIZE      (SIZE),
        .DATA_WIDTH(DATA_WIDTH)
    ) u_de_diagonalizer (
        .clk             (clk),
        .rst_n           (rst_n),
        .data_in         (data_in),
        .input_valid_i   (ia_calc_done),
        .data_out        (de_diag_data_out),
        .data_valid_o    (de_diag_data_valid),
        .tile_calc_over_o(de_diag_tile_calc_over)
    );

    always_comb begin
        for (int lane_idx = 0; lane_idx < SIZE; lane_idx++) begin
            data_out[lane_idx] = de_diag_data_valid ?
                                 de_diag_data_out[lane_idx] :
                                 fifo_data_out[lane_idx];
        end
    end

    // acc_data_valid and tile_calc_over are owned only by de_diagonalizer.
    assign acc_data_valid = de_diag_data_valid;
    assign tile_calc_over = de_diag_tile_calc_over;
endmodule
