// Auto-generated for case: rand_1_11
localparam int TC_K = 21;
localparam int TC_M = 21;
localparam int TC_BASE_ADDR = 32'h00000100;
localparam int TC_NUM_BLOCKS = 3;
localparam int TC_LAST_BLOCK_ELEMS = 5;
localparam int TC_SEQ_LEN = 4;
localparam int TC_LAST_LOOP = 0;
localparam int TC_GRANT_BP_EN = 0;
localparam int TC_GRANT_BP_CYCLES = 0;
localparam int TC_BP_TARGET_REQ_IDX = 0;
localparam int TC_BP_TARGET_REQ_CYCLES = 0;
localparam int TC_CHECK_VALID_DROP = 0;
localparam int TC_SRAM_DEPTH = 256;
